
export const STUDENT_DATASET = [
  { name: "Aarav", gender: "Male", age: 15, educationLevel: "Class 8", screenTime: 7.1, sleepDuration: 8.9, physicalActivity: 9.3, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Meera", gender: "Female", age: 25, educationLevel: "MSc", screenTime: 3.3, sleepDuration: 5, physicalActivity: 0.2, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Ishaan", gender: "Male", age: 20, educationLevel: "BTech", screenTime: 9.5, sleepDuration: 5.4, physicalActivity: 6.2, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Aditya", gender: "Male", age: 20, educationLevel: "BA", screenTime: 10.8, sleepDuration: 5.6, physicalActivity: 5.5, stressLevel: "High", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Anika", gender: "Female", age: 17, educationLevel: "Class 11", screenTime: 2.8, sleepDuration: 5.4, physicalActivity: 3.1, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Aditya", gender: "Male", age: 23, educationLevel: "MSc", screenTime: 8.6, sleepDuration: 8.4, physicalActivity: 0.1, stressLevel: "Low", anxiousBeforeExams: "No", performanceChange: "Improved" },
  { name: "Vivaan", gender: "Male", age: 22, educationLevel: "MTech", screenTime: 3.6, sleepDuration: 6.6, physicalActivity: 0.5, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Improved" },
  { name: "Arjun", gender: "Male", age: 25, educationLevel: "MTech", screenTime: 7, sleepDuration: 4.7, physicalActivity: 4.5, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Sai", gender: "Male", age: 20, educationLevel: "BA", screenTime: 4.8, sleepDuration: 5, physicalActivity: 7.9, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Improved" },
  { name: "Aadhya", gender: "Female", age: 16, educationLevel: "Class 9", screenTime: 8.9, sleepDuration: 8.4, physicalActivity: 7.8, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Improved" },
  { name: "Kavya", gender: "Female", age: 15, educationLevel: "Class 8", screenTime: 8, sleepDuration: 7.3, physicalActivity: 0.8, stressLevel: "Low", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Sai", gender: "Male", age: 23, educationLevel: "MSc", screenTime: 10.3, sleepDuration: 8.8, physicalActivity: 3.7, stressLevel: "High", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Myra", gender: "Female", age: 16, educationLevel: "Class 10", screenTime: 5.8, sleepDuration: 4.4, physicalActivity: 6.7, stressLevel: "High", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Meera", gender: "Female", age: 23, educationLevel: "MA", screenTime: 11.2, sleepDuration: 4.3, physicalActivity: 1.4, stressLevel: "Low", anxiousBeforeExams: "No", performanceChange: "Improved" },
  { name: "Shaurya", gender: "Male", age: 22, educationLevel: "MSc", screenTime: 8.9, sleepDuration: 7.8, physicalActivity: 5.3, stressLevel: "High", anxiousBeforeExams: "No", performanceChange: "Declined" },
  { name: "Arjun", gender: "Male", age: 21, educationLevel: "MA", screenTime: 11.1, sleepDuration: 8.5, physicalActivity: 2.1, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Declined" },
  { name: "Krishna", gender: "Male", age: 25, educationLevel: "MTech", screenTime: 11.5, sleepDuration: 5.6, physicalActivity: 0.4, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Diya", gender: "Female", age: 18, educationLevel: "Class 11", screenTime: 7, sleepDuration: 4.8, physicalActivity: 9.9, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Anika", gender: "Female", age: 16, educationLevel: "Class 9", screenTime: 9.7, sleepDuration: 7.2, physicalActivity: 1.5, stressLevel: "High", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Vivaan", gender: "Male", age: 18, educationLevel: "Class 11", screenTime: 2.5, sleepDuration: 7.9, physicalActivity: 2.8, stressLevel: "High", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Anika", gender: "Female", age: 20, educationLevel: "BTech", screenTime: 6.9, sleepDuration: 5.4, physicalActivity: 6.8, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Declined" },
  { name: "Reyansh", gender: "Male", age: 20, educationLevel: "BA", screenTime: 6, sleepDuration: 7.3, physicalActivity: 3.9, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Aarav", gender: "Male", age: 19, educationLevel: "BSc", screenTime: 7.6, sleepDuration: 7.7, physicalActivity: 2.7, stressLevel: "Low", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Kavya", gender: "Female", age: 15, educationLevel: "Class 8", screenTime: 11, sleepDuration: 8.5, physicalActivity: 1.9, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Improved" },
  { name: "Vihaan", gender: "Male", age: 17, educationLevel: "Class 11", screenTime: 3, sleepDuration: 4.3, physicalActivity: 8.6, stressLevel: "High", anxiousBeforeExams: "No", performanceChange: "Improved" },
  { name: "Anika", gender: "Female", age: 26, educationLevel: "MTech", screenTime: 4.7, sleepDuration: 6.8, physicalActivity: 9.6, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Myra", gender: "Female", age: 24, educationLevel: "MTech", screenTime: 9.9, sleepDuration: 7.9, physicalActivity: 0.7, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Declined" },
  { name: "Shaurya", gender: "Male", age: 24, educationLevel: "MTech", screenTime: 3.2, sleepDuration: 8.2, physicalActivity: 0.9, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Improved" },
  { name: "Arjun", gender: "Male", age: 18, educationLevel: "Class 11", screenTime: 7.9, sleepDuration: 4.7, physicalActivity: 1.6, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Kavya", gender: "Female", age: 17, educationLevel: "Class 11", screenTime: 7.9, sleepDuration: 4.9, physicalActivity: 3.2, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Reyansh", gender: "Male", age: 18, educationLevel: "Class 11", screenTime: 5.4, sleepDuration: 4.6, physicalActivity: 8.4, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Declined" },
  { name: "Arjun", gender: "Male", age: 16, educationLevel: "Class 9", screenTime: 2.4, sleepDuration: 8.5, physicalActivity: 8.7, stressLevel: "Low", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Kavya", gender: "Female", age: 19, educationLevel: "BA", screenTime: 9.5, sleepDuration: 4.5, physicalActivity: 1.1, stressLevel: "High", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Ira", gender: "Female", age: 20, educationLevel: "BSc", screenTime: 11.4, sleepDuration: 8.8, physicalActivity: 7.4, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Aadhya", gender: "Female", age: 18, educationLevel: "Class 12", screenTime: 10.6, sleepDuration: 8.6, physicalActivity: 8.8, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Anika", gender: "Female", age: 20, educationLevel: "BSc", screenTime: 10.6, sleepDuration: 6.4, physicalActivity: 8.2, stressLevel: "High", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Sai", gender: "Male", age: 18, educationLevel: "Class 12", screenTime: 11.7, sleepDuration: 8.6, physicalActivity: 6.8, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Krishna", gender: "Male", age: 22, educationLevel: "BSc", screenTime: 6.7, sleepDuration: 6.5, physicalActivity: 6.8, stressLevel: "Low", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Shaurya", gender: "Male", age: 25, educationLevel: "MSc", screenTime: 8.3, sleepDuration: 7.6, physicalActivity: 6.8, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Aarav", gender: "Male", age: 21, educationLevel: "MTech", screenTime: 6.6, sleepDuration: 8.3, physicalActivity: 7.6, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Improved" },
  { name: "Kavya", gender: "Female", age: 23, educationLevel: "MA", screenTime: 5.6, sleepDuration: 8.1, physicalActivity: 5.5, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Meera", gender: "Female", age: 20, educationLevel: "BTech", screenTime: 2.5, sleepDuration: 4.7, physicalActivity: 1.1, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Improved" },
  { name: "Aadhya", gender: "Female", age: 16, educationLevel: "Class 9", screenTime: 7.8, sleepDuration: 6.9, physicalActivity: 2, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Saanvi", gender: "Female", age: 23, educationLevel: "MSc", screenTime: 11.9, sleepDuration: 5.1, physicalActivity: 3, stressLevel: "High", anxiousBeforeExams: "Yes", performanceChange: "Improved" },
  { name: "Riya", gender: "Female", age: 15, educationLevel: "Class 9", screenTime: 2.4, sleepDuration: 6.6, physicalActivity: 5.4, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Rishi", gender: "Other", age: 16, educationLevel: "Class 10", screenTime: 9.4, sleepDuration: 6.2, physicalActivity: 5.1, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Declined" },
  { name: "Riya", gender: "Female", age: 21, educationLevel: "BSc", screenTime: 7.9, sleepDuration: 6.8, physicalActivity: 9.6, stressLevel: "Medium", anxiousBeforeExams: "No", performanceChange: "Same" },
  { name: "Shaurya", gender: "Male", age: 21, educationLevel: "BA", screenTime: 9.3, sleepDuration: 7.3, physicalActivity: 3, stressLevel: "Medium", anxiousBeforeExams: "Yes", performanceChange: "Same" },
  { name: "Vihaan", gender: "Male", age: 21, educationLevel: "BTech", screenTime: 8, sleepDuration: 8.5, physicalActivity: 9.1, stressLevel: "High", anxiousBeforeExams: "No", performanceChange: "Declined" },
  { name: "Arjun", gender: "Male", age: 24, educationLevel: "MA", screenTime: 5.1, sleepDuration: 5.4, physicalActivity: 5.7, stressLevel: "Low", anxiousBeforeExams: "Yes", performanceChange: "Same" }
];
